spring:
  profiles:
    active: dev
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    password: 123456
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true

security:
  user:
    name: admin
    password: admin
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
kcloud:
  server:
    eureka:
      port: 8761
      hostname: localhost
      serviceUrl: http://admin:admin@localhost:8761/eureka/
    conf:
      port: 8080
      hostname: localhost
      serviceUrl: http://localhost:8080
    gateway:
      port: 80
      hostname: localhost
    monitor:
      port: 8010
      hostname: localhost
      serviceUrl: localhost:8010
    zipkin:
      port: 8020
      hostname: localhost
      serviceUrl: http://localhost:8020
    provider:
      ehc:
        port: 8040
        hostname: localhost
      mdc:
        port: 8030
        hostname: localhost
      omc:
        port: 8050
        hostname: localhost
      opc:
        port: 8070
        hostname: localhost
      tpc:
        port: 8060
        hostname: localhost
      uac:
        port: 8000
        hostname: localhost
    web:
      mall:
        port: 9000
        hostname: localhost
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: smtp.sina.com
    username: 'your email address'
    password: 'your email password'
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: 47.96.173.142:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'your qiniu accessKey'
      secretKey: 'your qiniu secretKey'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'your qiniu oss public host'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/