spring:
  profiles:
    active: pro
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    password: 
    port: 6379
    timeout: 1000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    baseUrl: jdbc:mysql://localhost:3306
    username: root
    password: kcloud_mysql_aliyun113
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true

security:
  user:
    name: admin
    password: admin
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
kcloud:
  zookepeer:
    hostname: localhost
    port: 2181
  server:
    eureka:
      port: 8761
      hostname: localhost
      serviceUrl: http://admin:admin@localhost:8761/eureka/
    conf:
      port: 8080
      hostname: localhost
      serviceUrl: http://localhost:8080
    gateway:
      port: 8888
      hostname: localhost
    monitor:
      port: 8010
      hostname: localhost
      serviceUrl: localhost:8010
    zipkin:
      port: 8020
      hostname: localhost
      serviceUrl: http://localhost:8020
    provider:
      uac:
        port: 8000
        hostname: localhost
      opc:
        port: 8030
        hostname: localhost
      tpc:
        port: 8040
        hostname: localhost
      advideo:
        port: 8051
        hostname: localhost
      adbid:
        port: 8052
        hostname: localhost
      adfriends:
        port: 8053
        hostname: localhost
      adprofit:
        port: 8054
        hostname: localhost

    web:
      mall:
        port: 9000
        hostname: localhost
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: smtp.163.com
    username: kuyuntech@163.com
    password: kuyuntech2016
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: LTAI2flAE5PmIbSC
      accessKeySecret: NVK3zlsUCZddv0M8fG9NVXydWK3IwR
    rocketMq:
      namesrvAddr: 47.96.173.142:9876
    sms:
      signName: 灵动视频
      registerTemplateCode: SMS_135802426
      regionId: cn-shenzhen
      endpoint:
      endpointName: cn-shenzhen
      product: Dysmsapi
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'your qiniu accessKey'
      secretKey: 'your qiniu secretKey'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'your qiniu oss public host'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/